import type { WordListCategory } from "./types";

export const presetCategories: ReadonlyArray<WordListCategory> = Object.freeze([
  {
    id: "footballers",
    name: "Futbolistas",
    words: ["Coscu", "Momo", "La Cobra", "Davoo Xeneize",
"Spreen", "Carrera", "Rober Galati", "Papo MC",
"Luquita Rodríguez", "Robleis", "Markito Navaja", "Santutu",
"Brunenger", "Joaco López", "Fran MG", "Mica Suárez",
"Goncho", "Oscu", "Yao Cabrera", "Kevsho",
"Marti Benza", "LIT killah", "Duki", "Nicki Nicole",
"Bizarrap", "Luck Ra", "Tiago PZK", "FMK", "Nacho Castañares", "Julieta Poggio", "La Tora",
"Messi", "Maradona", "Riquelme", "Scaloni",
"Tevez", "Kun Agüero", "Dibu Martínez", "Otamendi",
"Migue Granados", "Nati Jota", "Pachu Peña", 
"Yayo", "Pablo Granados", "José María Listorti", 
"Marley", "Susana Giménez", "Mirtha Legrand", "Wanda Nara",
"Ricardo Fort", "Guido Kaczka", "Darío Barassi", "Tinelli",
"Julio Bocca", "Lali", "Tini", "María Becerra",
"Fede Vigevani", "Ian Lucas", "Tomas Mazza",
"Coker", "Farfadox", "Byking", "Zeko",
"Vorterix", "Olga", "Luzu", "Gelatina",
"El Demente", "Mica Viciconte", 
"Lucas Upstein", "Lucas Spadafora", "Trinche", "Westcol",
"Auron", "Ibai", "TheGrefg", "Rubius",
"Rivers", "Juan Guarnizo", "Arigameplays", "El Mariana",
"Quackity", "Vegetta", "Willyrex", "Fernanfloo",
"Germán Garmendia", "HolaSoyGerman", "Dross", "Luisito Comunica",
"Roro", "Peldanyos", "IlloJuan", "DjMaRiiO",
"Xokas", "ByViruzz", "Ampeter", "Perxitaa",
"Nimu", "Knekro", "Cristinini", "Mayichi",
"Boffe GP", "Tomás Rebord", 
"Coscu", "Spreen", "Momo", "Robleis",
"Bizarrap", "Duki", "LIT killah", "Tiago PZK",
"Messi", "Dibu Martínez", "Scaloni", "Kun Agüero",
"Marley", "Barassi", "Guido Kaczka", "Tinelli",
"Luquita Rodríguez", "Migue Granados", "Nati Jota", "Yayo",
"Oscu", "Santutu", "Carrera", "Brunenger",
"Westcol", "Rivers", "Auron", "Ibai",
"Rubius", "Xokas", "DjMaRiiO", "IlloJuan",
"Nicki Nicole", "Tini", "Lali", "María Becerra",
"Ricardo Fort", "Wanda Nara", "Susana Giménez", "Mirtha Legrand",
"Fede Vigevani", "Tomás Mazza", "king",
"Riquelme", "Tevez", "Maradona", "Otamendi",
"Papo MC", "Trueno", "Wos", "Acru",
"FMK", "Luck Ra", "Emilia", "Rusherking",
"Goncho", "Kevsho", "Mica Suárez", "Marti Benza",
"Rebord", "Pachu Peña"],
    preset: true,
  },
  {
    id: "animals",
    name: "Animales",
    words: ["tigre", "elefante", "delfín", "panda"],
    preset: true,
  },
]);
